[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals", "-C", "link-arg=--shared-memory"]

[toolchain]
channel = "nightly"
components = [ "rust-src" ]
targets = [ "wasm32-unknown-unknown" ]

[unstable]
build-std = ["std", "panic_abort"]
